wip: build

diff --git a/app/Dockerfile.prod b/app/Dockerfile.prod
--- a/app/Dockerfile.prod
+++ b/app/Dockerfile.prod
@@ -1,4 +1,4 @@
-FROM node:18-alpine AS builder
+FROM node:22-alpine AS builder
 
 WORKDIR /app
 
@@ -6,9 +6,10 @@ WORKDIR /app
 COPY package*.json ./
 COPY nuxt.config.ts ./
 COPY tsconfig.json ./
+COPY themes/* ./themes/
 
 # Installer les dépendances
-RUN npm ci --only=production
+RUN npm ci 
 
 # Copier le code source
 COPY . .
@@ -17,11 +18,12 @@ COPY . .
 RUN npm run build
 
 # === Image de production ===
-FROM node:18-alpine AS runtime
+FROM node:22-alpine AS runtime
 
 # Créer un utilisateur non-root
 RUN addgroup -g 1001 -S nodejs
 RUN adduser -S nuxt -u 1001
+RUN apk add --no-cache curl
 
 WORKDIR /app
 
@@ -41,7 +43,10 @@ ENV NUXT_HOST=0.0.0.0
 ENV NUXT_PORT=3000
 
 # Health check script
-COPY --chown=nuxt:nodejs healthcheck.js /app/
-RUN chmod +x /app/healthcheck.js
+# COPY --chown=nuxt:nodejs healthcheck.js /app/
+# RUN chmod +x /app/healthcheck.js
+
+# HEALTHCHECK --interval=10s --timeout=3s --start-period=5s --retries=3 \
+#   CMD curl -f http://localhost:3000 || exit 1
 
 CMD ["node", ".output/server/index.mjs"]
